2020-04-08 12:24:56,467 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2020-04-08 12:24:56,471 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\khawar\AppData\Local\Programs\Python\Python37\lib\site-packages\instabot\bot\bot.py
2020-04-08 12:24:56,471 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-04-08 12:24:57,269 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-04-08 12:24:58,484 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-04-08 12:24:59,235 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-04-08 12:24:59,957 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-04-08 12:25:01,999 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-04-08 12:25:01,999 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "The password you entered is incorrect. Please try again.", "invalid_credentials": true, "error_title": "Incorrect password for ashiqa_saona", "buttons": [{"title": "Try Again", "action": "dismiss"}], "status": "fail", "error_type": "bad_password"}'
2020-04-08 12:25:01,999 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2020-04-08 12:25:01,999 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: The password you entered is incorrect. Please try again.
2020-04-08 12:25:02,003 - instabot version: 0.117.0 (api) - INFO - Error type: bad_password
2020-04-08 12:25:02,007 - instabot version: 0.117.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-04-08 12:25:02,007 - instabot version: 0.117.0 (api) - INFO - Username or password is incorrect.
2020-04-08 12:25:04,867 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2020-04-08 12:25:04,867 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:\Users\khawar\Desktop\Desktop data\Work with Dawar Bhai\5 - Social Site Posting Proof\social\social - two\media\temp\dog_RMsuTfF.jpg' is not uploaded.
